export function renderDetailedCss() {
	return [
		"#printArea[data-layout=detailed]{--cv-accent:#3e6c9e;--cv-rule:#d6d3d1;",
		"--cv-ink:#1c1917;--cv-soft:#57534e;color:var(--cv-ink)}",
		"#printArea[data-layout=detailed] .page{padding:9mm 11mm}",
		"#printArea[data-layout=detailed] main{margin-inline:0}",
		"#printArea[data-layout=detailed] #contactBox{background:none;padding-inline:0}",
		".cv-header{background:none;text-align:center}",
		".cv-contact{font-size:12px;line-height:1.6}",
		".cv-links{font-size:12px;line-height:1.6}",
		".cv-contact a,.cv-links a{color:var(--cv-accent)}",
		".cv-sep{margin:0 6px;color:var(--cv-soft)}",
		".cv-header h1{font-size:28px;line-height:1.2;font-weight:600;color:#111}",
		".cv-header h2{font-size:16px;color:var(--cv-accent);margin-bottom:3px}",
		".cv-summary{text-align:left;border-top:1.5px solid #57534e;margin-top:7px;",
		"padding-top:7px;font-size:13px;line-height:1.45}",
		".cv-main{font-size:13px;line-height:1.4}",
		".cv-heading{font-variant:small-caps;letter-spacing:.05em;font-size:16px;",
		"color:var(--cv-accent);border-bottom:1px solid var(--cv-rule);",
		"margin:10px 0 6px;padding-bottom:2px}",
		".cv-heading a{color:inherit}",
		".cv-row{display:flex;justify-content:space-between;align-items:baseline;gap:12px}",
		".cv-role{font-weight:600;font-size:13.5px}",
		".cv-dates{font-weight:600;font-size:12.5px;white-space:nowrap}",
		".cv-duration{font-weight:400;font-size:11.5px;color:var(--cv-soft)}",
		".cv-sub{font-style:italic;color:var(--cv-soft)}",
		".cv-sub .cv-dates,.cv-location{font-weight:400;font-size:12px}",
		".cv-org{font-size:13px}",
		".cv-org a{color:inherit}",
		".cv-muted{color:var(--cv-soft)}",
		".cv-bullets{list-style:disc;margin:2px 0 4px;padding-left:16px}",
		".cv-bullets li{margin:1px 0}",
		".cv-bullets li::marker{color:#a8a29e}",
		".cv-tech{font-size:11.5px;color:var(--cv-soft);margin:1px 0 4px}",
		".cv-tech h5{display:inline;font-weight:600}",
		".cv-desc{font-size:11.5px;color:var(--cv-soft);margin-bottom:3px}",
		".cv-item{margin-bottom:6px}",
		".cv-skill{display:grid;grid-template-columns:11.5rem 1fr;column-gap:10px;",
		"margin-bottom:2px}",
		".cv-skill h3{font-weight:600}",
		"@media screen{",
		"#printArea[data-layout=detailed]{display:flex;flex-direction:column;gap:20px;",
		"height:auto;min-height:auto;box-shadow:none;border-radius:0;overflow:visible;background:none}",
		"body{counter-reset:page}",
		".page{width:100%;min-height:var(--resume-page-height);position:relative;",
		"background-color:var(--resume-page-background);box-shadow:0 0 5px rgba(0,0,0,20%);",
		"border-radius:10px;overflow:hidden}",
		'.page::after{content:"Page " counter(page);counter-increment:page;position:absolute;',
		"bottom:10px;right:20px;font-size:10px;color:var(--resume-muted)}",
		"}",
		"@media print{",
		"#printArea[data-layout=detailed]{width:100%;min-width:0;height:auto}",
		"#printArea[data-layout=detailed] #phoneBox{display:inline!important}",
		".page{box-shadow:none;border-radius:0;min-height:auto;page-break-after:always;break-after:page}",
		".page:last-child{page-break-after:auto;break-after:auto}",
		".page::after{display:none!important}",
		"h2,h3{page-break-after:avoid;break-after:avoid}",
		"[data-item-id]{page-break-inside:avoid;break-inside:avoid}",
		"*{-webkit-print-color-adjust:exact;print-color-adjust:exact}",
		"}",
	].join("");
}
