export type LayoutTheme = {
	page: Record<string, string>;
	theme: Record<string, string>;
	typography: Record<string, string>;
};

export function renderThemeCss({ page, theme, typography }: LayoutTheme) {
	return [
		`:root{--resume-primary:${theme.primary};`,
		`--resume-primary-hover:${theme.primaryHover ?? theme.primary};`,
		`--resume-primary-focus:${theme.primaryFocus ?? theme.primary};`,
		`--resume-page-width:${page.width};--resume-page-height:${page.height};`,
		`--resume-screen-background:${theme.screenBackground};`,
		`--resume-screen-background-dark:${theme.screenBackgroundDark ?? theme.screenBackground};`,
		`--resume-page-background:${theme.pageBackground};`,
		`--resume-header-background:${theme.headerBackground};`,
		`--resume-contact-background:${theme.contactBackground};`,
		`--resume-text:${theme.text};--resume-heading:${theme.heading};`,
		`--resume-muted:${theme.muted};--resume-body-font:${typography.bodyFont};`,
		`--resume-rtl-font:${typography.rtlFont};`,
		`--resume-name-size:${typography.nameSize};`,
		`--resume-title-size:${typography.titleSize};`,
		`--resume-body-size:${typography.bodySize};`,
		`--resume-detail-size:${typography.detailSize};`,
		`--resume-body-line-height:${typography.bodyLineHeight};`,
		`--resume-screen-padding:${page.screenPadding};`,
		`--resume-outer-margin:${page.outerMargin};`,
		`--resume-column-gap:${page.columnGap};`,
		`--resume-left-column:${page.leftColumn};`,
		`--resume-right-column:${page.rightColumn};}`,
		"body{font-family:var(--resume-body-font)}",
		"html[lang=fa] body{font-family:var(--resume-rtl-font)}",
		"#printArea{background-color:var(--resume-page-background)}",
		"header{background-color:var(--resume-header-background)}",
		"#contactBox{background-color:var(--resume-contact-background);padding-inline:var(--resume-outer-margin)}",
		"#printArea .text-stone-600{color:var(--resume-text)}",
		"#printArea .text-stone-500{color:var(--resume-muted)}",
		"#printArea .text-black{color:var(--resume-heading)}",
		"#printArea .text-3xl{font-size:var(--resume-name-size)}",
		"#printArea .text-xl{font-size:var(--resume-title-size)}",
		"#printArea .text-sm{font-size:var(--resume-body-size)}",
		"#printArea .text-xs{font-size:var(--resume-detail-size)}",
		"#printArea .leading-snug{line-height:var(--resume-body-line-height)}",
		"header>div:first-child{margin:var(--resume-outer-margin);margin-bottom:1rem}",
		"main{margin-inline:var(--resume-outer-margin)}",
		"main>:first-child{flex-basis:var(--resume-left-column)}",
		"main>:last-child{flex-basis:var(--resume-right-column)}",
		".space-x-4>:not([hidden])~:not([hidden]){margin-left:var(--resume-column-gap)}",
		".text-cyan-600{color:var(--resume-primary)}",
		".bg-cyan-600{background-color:var(--resume-primary)}",
		".hover\\:text-cyan-800:hover{color:var(--resume-primary-hover)}",
		".hover\\:bg-cyan-800:hover{background-color:var(--resume-primary-hover)}",
		".focus\\:bg-cyan-900:focus{background-color:var(--resume-primary-focus)}",
		"@media screen{body{background-color:var(--resume-screen-background)}",
		"#pageContainer{padding:var(--resume-screen-padding)}",
		"#printArea{width:var(--resume-page-width);min-width:var(--resume-page-width);",
		"height:var(--resume-page-height);min-height:var(--resume-page-height)}}",
		"@media screen and (prefers-color-scheme:dark){body{background-color:var(--resume-screen-background-dark)}}",
	].join("");
}
